name: Add discussion comment

on:
  workflow_dispatch:

permissions:
  contents: read
  discussions: write

jobs:
  add_discussion_comment:
    uses: route06/actions/.github/workflows/add_discussion_comment.yml@draft-TomckySan-add-discussion-comment-workflow
    with:
      discussion_id: "D_kwDOMRygUc4AaVhV"
      comment_seed_path: "_templates/seed.jsonl"
