name: Add discussion comment

on:
  workflow_dispatch:

jobs:
  add_discussion_comment:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      TZ: "Asia/Tokyo"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run script
        env:
         DISCUSSION_ID: "17"
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require("fs");

            const { DISCUSSION_ID } = process.env;

            // replace_values.jsonlに埋め込み値を入れとく
            const replace_values = fs.readFileSync("./_templates/replace_values.jsonl", "utf8")
              .trim()
              .split("\n")
              .map(JSON.parse);

            const template = fs.readFileSync("./_templates/test.md", "utf8")

            for await (const replace_value of replace_values) {
              // TODO: ここの変数どうしようかな。。。
              // const { project_name, category_name, project_type, assignees } = replace_value;

              const body = template
                .replace("{{ title }}", "たいとる")
                .replace("{{ foo }}", "ふー");

              await createDisussionComment(github, DISCUSSION_ID, body);
            }
