name: Create discussion

on:
  workflow_dispatch:

env:
  # NOTE: MTG開催曜日に合わせて変更してください
  TARGET_DAY: "wednesday"

jobs:
  get_next_meeting_date:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      TZ: "Asia/Tokyo"
    steps:
      - name: Get next meeting date
        id: get_date
        run: |
          target_date=$(date -d "next $TARGET_DAY" +%Y/%m/%d)
          echo "target_date=$target_date" >> "$GITHUB_OUTPUT"
    outputs:
      target_date: ${{ steps.get_date.outputs.target_date }}

  create_discussion:
    needs: get_next_meeting_date
    uses: route06/actions/.github/workflows/create_discussion.yml@update-create-discussion-workflow-1
    with:
      title: ${{ needs.get_next_meeting_date.outputs.target_date }} Meeting Title
      discussion_category_slug: meeting-notes
      description_template_path: _templates/weekly_meeting_discussion/test.md