name: Get next scheduled date

on:
  workflow_dispatch:

jobs:
  get_next_daily_scheduled_date:
    uses: route06/actions/.github/workflows/get_next_scheduled_date.yml@add-get-next-scheduled-date-workflow
    with:
      target_schedule: daily

  get_next_weekly_scheduled_date:
    uses: route06/actions/.github/workflows/get_next_scheduled_date.yml@add-get-next-scheduled-date-workflow
    with:
      target_schedule: weekly
      target_day: wednesday
  
  get_next_monthly_scheduled_date:
    uses: route06/actions/.github/workflows/get_next_scheduled_date.yml@add-get-next-scheduled-date-workflow
    with:
      target_schedule: monthly
      target_date: "10"

  get_next_yearly_scheduled_date:
    uses: route06/actions/.github/workflows/get_next_scheduled_date.yml@add-get-next-scheduled-date-workflow
    with:
      target_schedule: yearly
      target_yearly_date: "07-20"

  log_result:
    runs-on: ubuntu-latest
    needs: [get_next_daily_scheduled_date,get_next_weekly_scheduled_date,get_next_monthly_scheduled_date,get_next_yearly_scheduled_date]
    steps:
      - name: Log the next scheduled date
        run: |
          echo "The next daily schedule date is: ${{ needs.get_next_daily_scheduled_date.outputs.next_scheduled_date }}"
          echo "The next weekly schedule date is: ${{ needs.get_next_weekly_scheduled_date.outputs.next_scheduled_date }}"
          echo "The next monthly schedule date is: ${{ needs.get_next_monthly_scheduled_date.outputs.next_scheduled_date }}"
          echo "The next yearly schedule date is: ${{ needs.get_next_yearly_scheduled_date.outputs.next_scheduled_date }}"