name: Get next scheduled date

on:
  workflow_dispatch:

jobs:
  get_next_scheduled_date:
    uses: route06/actions/.github/workflows/get_next_scheduled_date.yml@test-calculate-next-date
    with:
      target_schedule: weekly
  
  log_result:
    runs-on: ubuntu-latest
    needs: get_next_scheduled_date
    steps:
      - name: Log the calculated next scheduled date
        run: |
          echo "The calculated next schedule date is: ${{ needs.get_next_scheduled_date.outputs.next_scheduled_date }}"