name: Set Due Date in GitHub Project

on:
  issues:
    types: [opened, edited]

permissions: write-all

jobs:
  set_due_date:
    runs-on: ubuntu-latest

    steps:
      - name: Extract due date from issue description
        id: extract_due_date
        run: |
          due_date=$(echo "${{ github.event.issue.body }}" | sed -n '/### テスト1/,/###/p' | sed '1d;$d' | tr -d '\n')
          echo "Due date: $due_date"
          echo "due_date=$due_date" >> $GITHUB_ENV

      - name: Generate token
        id: generate-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_PEM }}

      - name: Get project data
        env:
          GH_TOKEN: ${{ steps.generate-token.outputs.token }}
          ORGANIZATION: YOUR_ORGANIZATION
          PROJECT_NUMBER: YOUR_PROJECT_NUMBER
        run: |
          gh api graphql -f query='
          query($org: String!, $number: Int!) {
            organization(login: $org){
              projectV2(number: $number) {
                id
                fields(first:20) {
                  nodes {
                    ... on ProjectV2Field {
                      id
                      name
                    }
                    ... on ProjectV2SingleSelectField {
                      id
                      name
                      options {
                        id
                        name
                      }
                    }
                  }
                }
              }
            }
          }' -f org=$ORGANIZATION -F number=$PROJECT_NUMBER > project_data.json
          echo 'PROJECT_ID='$(jq '.data.organization.projectV2.id' project_data.json) >> $GITHUB_ENV
          echo 'DATE_FIELD_ID='$(jq '.data.organization.projectV2.fields.nodes[] | select(.name== "Date posted") | .id' project_data.json) >> $GITHUB_ENV
          echo 'STATUS_FIELD_ID='$(jq '.data.organization.projectV2.fields.nodes[] | select(.name== "Status") | .id' project_data.json) >> $GITHUB_ENV
          echo 'TODO_OPTION_ID='$(jq '.data.organization.projectV2.fields.nodes[] | select(.name== "Status") | .options[] | select(.name=="Todo") |.id' project_data.json) >> $GITHUB_ENV

      - name: Add issue to GitHub Project
        uses: actions/github-script@v7
        id: add_to_project
        with:
          github-token: ${{ steps.generate-token.outputs.token }}
          script: |
            const projectId = 'PVT_kwHOADXm_M4AkpWI';
            const contentId = context.payload.issue.node_id;

            const response = await github.graphql(`
              mutation($projectId: ID!, $contentId: ID!) {
                addProjectV2ItemById(input: {projectId: $projectId, contentId: $contentId}) {
                  item {
                    id
                  }
                }
              }
            `, {
              projectId: projectId,
              contentId: contentId,
            });

            const itemId = response.addProjectV2ItemById.item.id;
            console.log(`Item added to project with ID: ${itemId}`);
            return { itemId: itemId };

      - name: Set Due Date in GitHub Project
        if: env.due_date != ''
        uses: actions/github-script@v7
        with:
          script: |
            const projectId = '<your-project-id>';
            const itemId = context.payload.issue.node_id;
            const fieldId = '<your-custom-field-id>';  // カスタムフィールドのID

            await github.graphql(`
              mutation($projectId: ID!, $itemId: ID!, $fieldId: ID!, $dueDate: Date!) {
                updateProjectNextItemField(input: {
                  projectId: $projectId,
                  itemId: $itemId,
                  fieldId: $fieldId,
                  value: $dueDate
                }) {
                  projectNextItem {
                    id
                  }
                }
              }
            `, {
              projectId: projectId,
              itemId: itemId,
              fieldId: fieldId,
              dueDate: process.env.due_date,
            });
