name: Set Due Date in GitHub Project

on:
  issues:
    types: [opened, edited]

permissions: write-all

jobs:
  set_due_date:
    runs-on: ubuntu-latest

    steps:
      - name: Extract due date from issue description
        id: extract_due_date
        run: |
          due_date=$(echo "${{ github.event.issue.body }}" | sed -n '/### テスト1/,/###/p' | sed '1d;$d' | tr -d '\n')
          echo "Due date: $due_date"
          echo "due_date=$due_date" >> $GITHUB_ENV

      - name: Generate token
        id: generate-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_PEM }}

      - name: Add issue to GitHub Project
        uses: actions/github-script@v7
        id: add_to_project
        with:
          github-token: ${{ steps.generate-token.outputs.token }}
          script: |
            const projectId = 'PVT_kwDOCqYGf84AmW_O';
            const contentId = context.payload.issue.node_id;

            const response = await github.graphql(`
              mutation($projectId: ID!, $contentId: ID!) {
                addProjectV2ItemById(input: {projectId: $projectId, contentId: $contentId}) {
                  item {
                    id
                  }
                }
              }
            `, {
              projectId: projectId,
              contentId: contentId,
            });

            const itemId = response.addProjectV2ItemById.item.id;
            console.log(`Item added to project with ID: ${itemId}`);
            return { itemId: itemId };

      - name: Set Due Date in GitHub Project
        if: env.due_date != ''
        uses: actions/github-script@v7
        with:
          script: |
            const projectId = 'PVT_kwDOCqYGf84AmW_O';
            const itemId = context.payload.issue.node_id;
            const fieldId = 'PVTF_lADOCqYGf84AmW_OzgeR5_I';

            await github.graphql(`
              mutation($projectId: ID!, $itemId: ID!, $fieldId: ID!, $dueDate: Date!) {
                updateProjectV2ItemFieldValue(input: {
                  projectId: $projectId,
                  itemId: $itemId,
                  fieldId: $fieldId,
                  value: { date: $dueDate }
                }) {
                  projectV2Item {
                    id
                  }
                }
              }
            `, {
              projectId: projectId,
              itemId: itemId,
              fieldId: fieldId,
              dueDate: process.env.due_date,
            });
