name: Set Due Date in GitHub Project

on:
  issues:
    types: [opened, edited]

jobs:
  set_due_date:
    runs-on: ubuntu-latest

    steps:
      - name: Extract due date from issue description
        id: extract_due_date
        run: |
          description="${{ github.event.issue.body }}"
          due_date=$(echo "$description" | sed -n 's/^.*Due Date: \([0-9]\{4\}-[0-9]\{2\}-[0-9]\{2\}\).*$/\1/p')
          echo "due_date=$due_date" >> $GITHUB_ENV

      - name: Check if due date was found
        if: env.due_date != ''
        run: |
          echo "Due date found: ${{ env.due_date }}"

      - name: Set Due Date in GitHub Project
        if: env.due_date != ''
        uses: actions/github-script@v7
        with:
          script: |
            const projectId = '<your-project-id>';
            const itemId = context.payload.issue.node_id;
            const fieldId = '<your-custom-field-id>';  // カスタムフィールドのID

            await github.graphql(`
              mutation($projectId: ID!, $itemId: ID!, $fieldId: ID!, $dueDate: Date!) {
                updateProjectNextItemField(input: {
                  projectId: $projectId,
                  itemId: $itemId,
                  fieldId: $fieldId,
                  value: $dueDate
                }) {
                  projectNextItem {
                    id
                  }
                }
              }
            `, {
              projectId: projectId,
              itemId: itemId,
              fieldId: fieldId,
              dueDate: process.env.due_date,
            });
